feat(api): add model for club roles
BitByte-TPC/gymkhana pull request #118
Opened 2022-07-07 08:56 UTC by PranshuNayak

2022-07-07 09:02 UTC, PranshuNayak commented
@Samy-33 raised the PR

2022-07-07 10:44 UTC, Aksh-Bansal-dev commented on api/api/Roles/models.py
> +    ]
We should also add a role for core members as it is not necessary that only the coco or the coordinator will host an event.

2022-07-07 16:38 UTC, Samy-33 requested changes

2022-07-07 16:38 UTC, Samy-33 commented on api/api/Roles/models.py
> +    user = models.OneToOneField(User, on_delete=models.CASCADE)
Why are these `OneToOneFields`? A club can have multiple roles, and a user can have multiple roles as well.

2022-07-07 16:39 UTC, Samy-33 requested changes

2022-07-07 16:39 UTC, Samy-33 commented on api/api/Roles/apps.py
> +    label = 'api_Roles'
name and label must be lowercase.

2022-07-08 14:20 UTC, Samy-33 requested changes

2022-07-08 14:20 UTC, Samy-33 commented on api/api/Roles/models.py
> +    user = models.ManyToManyField(User, on_delete=models.CASCADE)
These should be `ForeignKeyFields`. Why?

club as a `ManyToManyField` means, 1 object of club will have multiple objects of `Role` class, and 1 object of `Role` will have multiple clubs associated with it.

Do we want that? No.

One object of `Role` class means: one relationship between club, user and the role_name. Hence `ForeignKeyField` makes more sense.

2022-07-10 13:01 UTC, Samy-33 approved these changes
LGTM

2022-07-10 13:01 UTC, merged