feat(api): add endpoint for creating users
BitByte-TPC/gymkhana pull request #166
Opened 2022-07-15 16:24 UTC by arminpatel

+ `view` : generic CreateAPI view
+ `Post` request at `/users/` for creating users
+ ` Serializers` 
  + Simple Model Serializers for `Faculty`, `Student` and `Staff`
  + These three serializers are nested inside `UserSerializer` and their `required` attribute is set to `False`
  + The `create` method then extracts data of each Serializer(if present) and the remaining data is used to create the user. And depending on the extracted data, the student, faculty and staff instances are created.
  +  The problem I was facing in this implementation was that a User could be only one of staff, faculty and student. I've have handled it by assuming only one or neither of them would be passed to the api. Let me know if the design could have been better.
+ `testing`: I have added some test to cover different scenarios like adding base User, Student, Faculty etc, and what should happen when invalid emails are provided

2022-07-15 16:29 UTC, Samy-33 commented
Left some comments on https://github.com/BitByte-TPC/gymkhana/pull/164.

Closing a PR if you mess something up in git and reopening a fresh PR is not good for multiple reasons:
1. You have to do this toiling task every time you mess up something in `git`.
2. Reviews done in the previous PR is kind of lost.
3. Git provides ways to do it in an easier way, so you should utilise that. 
    - [git reflog](https://www.atlassian.com/git/tutorials/rewriting-history/git-reflog#:~:text=Git%20keeps%20track%20of%20updates,git%20reset)
    - [git rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

2022-07-15 16:33 UTC, arminpatel commented
> Left some comments on #164.
> 
> Closing a PR if you mess something up in git and reopening a fresh PR is not good for multiple reasons:
> 
> 1. You have to do this toiling task every time you mess up something in `git`.
> 2. Reviews done in the previous PR is kind of lost.
> 3. Git provides easier ways to fix the mess up, so you should utilise that.
>    
>    * [git reflog](https://www.atlassian.com/git/tutorials/rewriting-history/git-reflog#:~:text=Git%20keeps%20track%20of%20updates,git%20reset)
>    * [git rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

Ok, will mind from next time. So should I fix and reopen #164 or keep this one?

2022-07-16 03:10 UTC, arminpatel commented
Tried to use pytest parametrize and fixtures but was thrown with the following error,

<img width="715" alt="Screenshot 2022-07-16 at 8 28 13 AM" src="https://user-images.githubusercontent.com/72291325/179336684-dce44e92-d830-4bdc-9897-8e1ea6b21331.png">

[my code](https://p.ip.fi/b6Ih)

Pytest fixtures and parametrize do not support django unittest.TestCase subclass
[reference](https://docs.pytest.org/en/latest/how-to/unittest.html#pytest-features-in-unittest-testcase-subclasses)
So is there any other way?

2022-07-16 03:39 UTC, Samy-33 commented
Have you tried placing `@parameterize` decorator below the `@django_db` decorator?

As decorator's order matters in python, it might be the issue.

- Don't use variables in the parameters list, just use the values. Readers have to go to the variable definition to know the value.

-`invalidEmailProvided`, `throwsBadRequest`

2022-07-16 04:10 UTC, arminpatel commented
> Have you tried placing `@parameterize` decorator below the `@django_db` decorator?
> 
> As decorator's order matters in python, it might be the issue.

Still getting the same error. [my code](https://p.ip.fi/JTks)

2022-07-16 04:16 UTC, Samy-33 commented
@arminpatel can you push your code, I will take a look.

2022-07-16 04:53 UTC, Samy-33 commented
@arminpatel let's use function based tests for `CreateUserView`

```python
@pytest.mark.parametrize('invalid_email', ['', 'someemail'])
@pytest.mark.django_db
def testUsersListView_invalidEmailsProvided_returnsHttp400(invalid_email):
    # given
    user = User.objects.create(
        email=primaryTestUserMail, first_name='Test', last_name='User')
    client = APIClient()
    client.force_authenticate(user)

    # when
    response1 = client.post(userCreationEndpoint, {'email': invalid_email},
                            format='json')

    # then
    assert response1.status_code == status.HTTP_400_BAD_REQUEST
```

2022-07-16 04:56 UTC, arminpatel commented
> @arminpatel let's use function based tests for `CreateUserView`
> We need to refactor all the tests to be in functional format instead of class based.

ok, I will make the changes

2022-07-16 05:25 UTC, arminpatel commented
@Samy-33 Made the changes.

2022-07-16 06:28 UTC, Samy-33 requested changes
Overall looks good, few minor improvements.

2022-07-16 06:28 UTC, Samy-33 commented on api/api/accounts/tests.py
> +    assert response.data['email'] == test_user_email
redundant check?

2022-07-16 06:28 UTC, Samy-33 commented on api/api/accounts/tests.py
> +@pytest.mark.parametrize('invalid_mail', ['test@user.com', '', 'testusersom'])
Let's add comment for each invalid email as to why it's invalid.

```python
@pytest.mark.parametrize('invalid_mail', [
    'test@user.com', # admin user 
    '', # empty email
    'testusersom' # invalid email format
])
```

2022-07-16 06:28 UTC, Samy-33 commented on api/api/accounts/views.py
> +from .models import User
use `get_user_model()`

2022-07-16 06:28 UTC, Samy-33 commented on api/api/accounts/tests.py
> +    client = APIClient()
nit: we can use `pytest.fixture` to create repetitive objects once.

```python
@pytest.mark.django_db
@pytest.fixture(scope='function')
def admin_user(django_user_model):
    return django_user_model.objects.create(email=primary_test_user_mail, first_name='Test', last_name='User', is_staff=True)

@pytest.fixture(scope='function')
def client():
    return APIClient()
```

And then use it like:
```python
@pytest.mark.django_db
def testCreateUserView_testPermission_nonAdminRequest_throwsForbidden(admin_user, client):
    ...
```

`pytest_django` also allows you to use `django_user_model` fixture to get `User` model: [Reference](https://pytest-django.readthedocs.io/en/latest/helpers.html#django-user-model)

2022-07-16 06:28 UTC, Samy-33 commented on api/api/accounts/tests.py
> +    print(response.data)
Remove print

2022-07-16 06:32 UTC, arminpatel commented on api/api/accounts/tests.py
> +    assert response.data['email'] == test_user_email
Yeah, thought more checks wouldn't hurt 😅 . I will remove them.

2022-07-16 08:03 UTC, Samy-33 approved these changes
Looks great. Good work @arminpatel

2022-07-16 08:04 UTC, merged