fix(ui): fetch clubs from api
BitByte-TPC/gymkhana pull request #167
Opened 2022-07-15 17:52 UTC by prajjwalkapoor

2022-07-16 18:10 UTC, prajjwalkapoor commented
@Samy-33 you can review this

2022-07-16 19:48 UTC, Samy-33 requested changes

2022-07-16 19:48 UTC, Samy-33 commented on ui/src/components/ClubsCarousel/index.tsx
> +  interface ClubsCarouselProps {
These are not Carousel props, so naming them so doesn't make sense. Maybe `ClubsCarouselData` sounds better?

2022-07-16 19:48 UTC, Samy-33 commented on ui/src/components/ClubsCarousel/index.tsx
> +  const CLUBS_API_URL = 'http://127.0.0.1:8000/clubs/';
Should not be hardcoded. Look at https://github.com/BitByte-TPC/gymkhana/blob/294716bc464488827e6d9e9d9aa55cb32ee02152/ui/src/api/googleOauth.ts#L34 for reference.

2022-07-16 19:48 UTC, Samy-33 commented on ui/src/components/ClubsCarousel/index.tsx
>          {data.map((club, i) => (
rename `i` to `index` for better readability.

2022-07-17 02:28 UTC, Samy-33 approved these changes
LGTM

2022-07-17 02:45 UTC, merged