Feat/dark mode
BitByte-TPC/gymkhana pull request #220
Opened 2022-08-22 16:54 UTC by Manie-oss

2022-08-23 16:27 UTC, Aksh-Bansal-dev requested changes
Make the background a little darker wherever we are using SVG background(Login, news carousel).
Also, the cards in the news carousel remain white when we switch to dark mode(which should not happen ideally).

2022-08-23 16:27 UTC, Aksh-Bansal-dev commented on ui/src/components/TopBar/index.tsx
> +  }
Use arrow functions. We should have a consistent code style.

2022-08-24 04:31 UTC, Manie-oss commented on ui/src/pages/Login/styles.module.scss
> +}
this we will be using once the svg for login screen(dark theme) is available on figma.

2022-08-24 16:22 UTC, Manie-oss commented on ui/src/components/TopBar/styles.module.scss
> +}
may I know the reason please!

2022-08-24 16:46 UTC, Aksh-Bansal-dev commented on ui/src/components/TopBar/styles.module.scss
> +}
When we switch to the dark mode, the background of the button remains white, which looks a little odd imo.

2022-08-25 14:32 UTC, Samy-33 commented on ui/src/components/TopBar/styles.module.scss
> +}
IMO, it looks good. As yellow object on a black background is weird.

2022-08-28 18:02 UTC, Samy-33 commented on ui/src/components/TopBar/styles.module.scss
> +}
@Aksh-Bansal-dev ping.

2022-08-29 03:54 UTC, Aksh-Bansal-dev commented on ui/src/components/TopBar/styles.module.scss
> +}
I was thinking of something like [this](https://i.ytimg.com/vi/x0hGQ3blksE/maxresdefault.jpg).
But it's fine for now, maybe we can change it later.

2022-08-29 04:03 UTC, Aksh-Bansal-dev commented on ui/src/pages/Login/styles.module.scss
> +}
I think, for now, we can do something like [this](https://www.figma.com/file/GjOEDxaZ4sT9mBr8A10IiA/Gymkhana?node-id=422%3A2).

2022-08-29 04:17 UTC, Aksh-Bansal-dev commented on ui/src/pages/Login/styles.module.scss
> +}
Please don't resolve conversations on your own. It just makes reviewing more difficult as the reviewer has to check all resolved conversations and check whether they are actually resolved or not.

2022-08-29 15:42 UTC, Aksh-Bansal-dev requested changes

2022-08-29 15:42 UTC, Aksh-Bansal-dev commented on ui/src/components/Layout/Layout.tsx
> +import {useState, useRef, useEffect, useContext} from 'react';
Are we using `useContext` hook here?

2022-08-29 15:42 UTC, Aksh-Bansal-dev commented on ui/src/components/NewsCarousel/styles.module.scss
> +  // background-color: var(--toggle-overlay);
Please remove unnecessary comments.

2022-08-29 15:42 UTC, Aksh-Bansal-dev commented on ui/src/components/ProfileCard/index.tsx
> +import {useContext} from 'react';
same

2022-08-29 15:42 UTC, Aksh-Bansal-dev commented on ui/src/components/Sidebar/Sidebar.tsx
> +import React, {useContext} from 'react';
same

2022-08-29 15:42 UTC, Aksh-Bansal-dev commented on ui/src/components/TopBar/styles.module.scss
> +  // border: 2px solid rgb(104, 103, 103);
remove this as well.

2022-08-29 15:42 UTC, Aksh-Bansal-dev commented on ui/src/pages/Home/index.tsx
> +import './styles.module.scss';
Do we need this now?

2022-08-29 15:42 UTC, Aksh-Bansal-dev commented on ui/src/pages/Home/styles.module.scss
> +
Please remove empty files.

2022-08-29 15:42 UTC, Aksh-Bansal-dev commented on ui/src/components/TopBar/index.tsx
> +const WebsiteTheme = 'website_theme';
All letters should be uppercase. 
```js
const LIGHT_MODE_VALUE = 'light_mode';
```

2022-08-30 03:53 UTC, Aksh-Bansal-dev requested changes

2022-08-30 03:53 UTC, Aksh-Bansal-dev commented on ui/src/components/Theme/index.tsx
> +export const Theme: any = () => {
Try not to use `any` type unless necessary. You can use `React.FC` here.
Also, `Theme` doesn't sound like a component, let's make it something like `ThemeButton`.

2022-08-30 12:56 UTC, Aksh-Bansal-dev approved these changes
LGTM

2022-08-30 13:02 UTC, merged

2022-08-30 15:11 UTC, Manie-oss commented
> LGTM

LGTMT