Updated link
BitByte-TPC/gymkhana pull request #54
Opened 2022-06-06 17:33 UTC by PrajwalBorkar

Fixes #45

2022-06-06 19:17 UTC, Samy-33 requested changes
1. Get the issue #45 assigned to you before you start working on the change.
2. Update your commit message to conform to the [guidelines](https://github.com/BitByte-TPC/gymkhana/blob/master/CONTRIBUTING.md#standard-commit-messages)

2022-06-06 19:17 UTC, Samy-33 commented on README.md
>  - [ui setup](https://github.com/BitByte-TPC/gymkhana/tree/master/ui)
please add readme # link to ui as well

2022-06-07 06:30 UTC, PrajwalBorkar commented
> 1. Get the issue #45 assigned to you before you start working on the change.
> 2. Update your commit message to conform to the [guidelines](https://github.com/BitByte-TPC/gymkhana/blob/master/CONTRIBUTING.md#standard-commit-messages)

Made the changes please review.

2022-06-07 07:25 UTC, Samy-33 commented
1. You've still not gotten the issue assigned.
2. Please squash your commits into one. And change the commit message.

2022-06-07 07:29 UTC, PrajwalBorkar commented
> 1. You've still not gotten the issue assigned.
> 2. Please squash your commits into one. And change the commit message.

Should I close the PR if issue is not assigned to me?

2022-06-07 07:31 UTC, Samy-33 commented
> Should I close the PR if issue is not assigned to me?

The issue is still not assigned to anyone so you can get it assigned to yourself.
Just comment on the issue that you'll be working on it. I will assign it to you.

2022-06-07 08:06 UTC, closed without merging