User model
BitByte-TPC/gymkhana pull request #82
Opened 2022-06-22 07:39 UTC by divyanshkhetan

2022-06-22 20:00 UTC, Samy-33 commented
@divyanshkhetan @Saksham-1508, please fix the linting errors.

2022-06-23 02:45 UTC, Samy-33 requested changes

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +# Create your models here.
this comment can be removed.

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +class UserManager(BaseUserManager):
Is this a duplicate? We already have `CustomUserManager` in `managers.py`

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +    gender = models.CharField(max_length=50, choices=Constants.SEX_CHOICES, default="M")
max_length 50 doesn't make sense. Keep it 10.

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +    objects = UserManager()
Should be `CustomUserModel`

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +        self.is_superuser = (self.is_superuser is True)
Q: What does `(self.is_active is True)` do?

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +    github = models.URLField(null=True, blank=True, default="www.github.com")
There should be a separate model for these: `StudentSocial`. And default should be null.

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +    # profile_img = models.ImageField(null=True)
Stale comment should be removed.

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +    # TODO: choices in department yet to be added
Create an issue and add the issue number in todo like: `TODO(#issueNumber): add choices in department`

2022-06-23 02:45 UTC, Samy-33 commented on api/api/accounts/models.py
> +    # profile_img = models.ImageField(null=True)
stale comment

2022-06-23 07:54 UTC, Samy-33 commented
Also, please remove empty files.

2022-06-23 09:59 UTC, divyanshkhetan commented
@Samy-33 sir, I have made the requested changes. Please review them. Thanks!

2022-06-23 11:05 UTC, Samy-33 requested changes

2022-06-23 11:05 UTC, Samy-33 commented on api/api/accounts/managers.py
> +            raise ValueError("User must have a password")
Throwing this exception here means we are forcing users to have passwords. As we are using OAuth2 for now. That means we will not use passwords and so this check can be skipped.

2022-06-23 11:05 UTC, Samy-33 commented on api/api/accounts/models.py
> +    linkedin = models.URLField(null=True, blank=True, default=None)
I don't think we need to specific default in this case. If `null=True` then it'll automatically be populated as `None` by default.

2022-06-23 17:29 UTC, Samy-33 approved these changes
LGTM

2022-06-23 17:48 UTC, Samy-33 requested changes

2022-06-23 17:48 UTC, Samy-33 commented on api/api/accounts/models.py
> +        self.is_superuser = (self.is_superuser is True)
I don't understand this and hence don't like it. Can you remove this?

2022-06-24 02:58 UTC, Samy-33 requested changes

2022-06-24 02:58 UTC, Samy-33 commented on api/api/accounts/models.py
> +        """For cpanel."""
Now we have this stale comment.

2022-06-24 07:48 UTC, Samy-33 approved these changes

2022-06-24 07:48 UTC, merged